### ISSUE TITLE
Модуль utils не найден

### ISSUE THREAD

**Issue by franchb** [vkantor/MIPT_Data_Mining_In_Action_2016#1]
При попытке работы с блокнотом получаю вот такую ошибку:

`ImportError: No module named utils`

Где можно найти этот модуль `utils`? 

Поиск приводит на [mlxtend](http://rasbt.github.io/mlxtend/user_guide/data/load_mnist/), но мне кажется, это немного не то.

**Comment by senya-ashukha** [comment]
Привет, речь идет про этот файл https://github.com/vkantor/MIPT_Data_Mining_In_Action_2016/blob/master/trends/hw0/utils.py 
 если запустишь ядро тетрадки в папке hw0 то все должно само подцепиться.

**Comment by franchb** [comment]
Спасибо! Клонировал весь репозиторий, картинки из `mnist` в `data` подгрузились.

**Comment by Sergey1983** [comment]
> если запустишь ядро тетрадки в папке hw0 то все должно само подцепиться.

а можно чутка попонятней для "тупых"?

**Comment by Sergey1983** [comment]
окей, т.е. алгоритм такой: скачиваем папку trends/hw0/, в ней создаем файл в котором будем писать код и запускаем этот файл. Все запустил, все работает, можно в следующий раз поподробнее описать, что куда подгрузить и откуда вызывать? Я думаю, я тут не один начинающий.
UPD: неа, не работает) видимо, сначала нужно вообще изучить, как работает GitHub?:)

**Comment by senya-ashukha** [comment]
@Sergey1983

> а можно чутка попонятней для "тупых"?

смотри, я имел ввиду что нужно зати в `trends/hw0` а там уже запустит `ipython2 notebook`

> окей, т.е. алгоритм такой: скачиваем папку trends/hw0/

неа, алгоритм такой `git clone репозиторий` -- для скачиваний, `git pull` для обновлений 
советую почитать git book  https://git-scm.com/book/ru/v1 первые 3 главы
