### ISSUE TITLE
Можете, пожалуйста, разблокировать гугл форму

### ISSUE THREAD

**Issue by andreybavt** [vkantor/MIPT_Data_Mining_In_Action_2016#13]
Привет! 
Можете, пожалуйста, разблокировать форму сдачи дз? Я начал заполнять значения, потом, видимо по ошибке засабмитил полупустую форму и теперь заполнить заново не даёт.

привязана к мэйлу : andreybavt@gmail.com

спасибо

**Comment by persiyanov** [comment]
Про какое домашнее задание Вы говорите? Если про тренды, то ваш сабмит дошел, все хорошо вроде бы.

**Comment by andreybavt** [comment]
Спасибо, да, про тренды. Тогда оставим как есть
