### ISSUE TITLE
В шаблоне кода не учитывается порядок просмотра 

### ISSUE THREAD

**Issue by tveritinova** [vkantor/MIPT_Data_Mining_In_Action_2016#16]
В task_template.ipynb (у индустрии в hw0) в recommend_by_  при равных частотах не учитывается порядок, в котором просматривались товары. В условии сказано, что нужно учитывать.

**Comment by ilirhin** [comment]
OrderedDict учитывает порядок

**Comment by tveritinova** [comment]
Хм, и правда. Показалось, что видела сессию, в которой не в том порядке было.
