### ISSUE TITLE
автоэнкодер бесконечно обрабатывает код

### ISSUE THREAD

**Issue by KITOAND** [vkantor/MIPT_Data_Mining_In_Action_2016#17]
Автоэнкодер бесконечно обрабатывает код, хотя на другом компе этот же код выдает результаты довольно быстро. jupiter notebook на macOS

**Comment by niksh** [comment]
1) Это происходит уже при обучении или ещё при импорте?
2) Насколько долго обрабатывает? Если нет GPU, процесс может быть сильно замедлен.

**Comment by KITOAND** [comment]
При обучении, когда должны печататься ошибки. Он вообще не заканчивает процесскакоето время пишется busy во вкладке, потом оно пропадает.GPU есть.

**Comment by niksh** [comment]
Можно попоробовать 2 вещи:
1) в $HOME/.theanorc убрать строчку device=gpuX (если она есть)
2) перенести код в скрипт и запустить из командной строки - посмотреть, что он выводит
У меня была аналогичная проблема при импорте theano. Процесс падал из за проблем с CUDA, а ячейка так и оставалась висеть в busy.
