### ISSUE TITLE
LaTex matplotlib

### ISSUE THREAD

**Issue by dopedlab** [vkantor/MIPT_Data_Mining_In_Action_2016#19]
Здравствуйте, возникает проблема при попытке использования LaTex в matplotlib: графики 3х элементарных функций из задания по Python рисуются отлично до тех пор, пока не используется LaTex. Если написать:

rc('text', usetex=True), 

то возникает ошибка 

RuntimeError: LaTeX was not able to process the following string:
'lp'
Here is the full report generated by LaTeX: 

<matplotlib.figure.Figure at 0x11501bf90>,

от которой спасает только перенесение всего кода в новый ноутбук. В чем может быть причина?

**Comment by ghost** [comment]
Для Debian/Ubuntu
http://stackoverflow.com/a/11357765
