### ISSUE TITLE
base/hw1 append_biases

### ISSUE THREAD

**Issue by stapko** [vkantor/MIPT_Data_Mining_In_Action_2016#20]
Не работает метод,а вообще не работает sparse.hstack()

`X_train_sample = X_train[:10000]
 y_train_sample = y_train[:10000]

 clf = LogisticRegression()
 clf.w = np.random.randn(X_train_sample.shape[1]+1) \* 2
 LogisticRegression.append_biases(X_train_sample)`

ValueError: could not broadcast input array from shape (10000,2000) into shape (10000)

![scr1](https://cloud.githubusercontent.com/assets/15112886/19705417/19a273a6-9b15-11e6-95fc-90261601f679.png)
![scr2](https://cloud.githubusercontent.com/assets/15112886/19705416/199f79bc-9b15-11e6-9204-ad56149febdc.png)

**Comment by dmylnikov** [comment]
проверь, что X_train, y_train - sparse matrices, их не надо преобразовывать в numpy.ndarray

**Comment by stapko** [comment]
Спасибо, помогло
