### ISSUE TITLE
np.random.choice

### ISSUE THREAD

**Issue by ghost** [vkantor/MIPT_Data_Mining_In_Action_2016#23]
Если я правильно понял, после того как мы разделили исходную выборку на тренировочную и тестовую, нам необходимо в logistic_regression.py разбить X_train и y_train на батчи размером 200 и высчитывать функцию ошибки на каждом батче, а не на каждом элементе. np.random.choice принимает на вход вектор. Собственно, вопрос: как обучающие sparse-матрицы преобразовать в вектор?

**Comment by lucidyan** [comment]
@meefasto 
Можно передать ему просто количество элементов в массиве, например так:
`batch_indices = np.random.choice(num_train, batch_size, replace=True)`
это шорткат для явной записи:
`batch_indices = np.random.choice(np.arange(num_train), batch_size, replace=True)`

**Comment by ghost** [comment]
@Lucidyan 
Премного сенкью
