### ISSUE TITLE
/base/hw1 Import error

### ISSUE THREAD

**Issue by klatzklatz** [vkantor/MIPT_Data_Mining_In_Action_2016#27]
from sklearn.model_selection import  train_test_split

ImportError: cannot import name cluster

Как с этим жить? или надо train_test_split брать из какой-то другой библиотеки?

**Comment by igor-prusov** [comment]
Скорее всего так:
from sklearn.cross_validation import train_test_split

В старых версиях train_test_split в другом месте лежит

**Comment by klatzklatz** [comment]
Теперь вот другая ошибка импорта

ImportError: cannot import name logger

**Comment by q121212** [comment]
Попробуй установить scipy
Пишут, что помогает (http://stackoverflow.com/questions/15274696/importerror-in-importing-from-sklearn-cannot-import-name-check-build)

**Comment by klatzklatz** [comment]
Спасибо
