### ISSUE TITLE
[trends] mid_func not defined

### ISSUE THREAD

**Issue by kirillbobyrev** [vkantor/MIPT_Data_Mining_In_Action_2016#3]
При запуске Cell с TSNE происходит ошибка. `mid_func` до этого и правда не определен, зато определен в Cell'е "Сдачи домашки". Не уверен как это было задумано, но надо либо определить её до TSNE, либо закинуть визуализацию TSNE уже после сдачи домашки.

``` python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-2683586f782c> in <module>()
----> 1 X_mid = mid_func(X_train)[0]
      2 X_tsne = TSNE(n_components=2, n_iter=200).fit_transform(X_mid[:2000])
      3 pylab.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y_train[:2000], cmap=pylab.cm.hot)

NameError: name 'mid_func' is not defined
```

**Comment by senya-ashukha** [comment]
Привет, определен смотрите ячейку 

`# Скомпилируем теано граф
train_func = ...
predi_func = ...
mid_func = ...`

**Comment by kirillbobyrev** [comment]
Ой, и правда.

Видимо, почему-то я её не запустил. Прошу прощения.
