### ISSUE TITLE
Вопрос по потоку данных

### ISSUE THREAD

**Issue by zachanton** [vkantor/MIPT_Data_Mining_In_Action_2016#33]
Какие должны быть ориентировочные желательные времена подсчета? В задании написано "в течении часа", но вроде как это очень много, самый простой алгоритм без учета особенностей каждого из потоков выдает мне ~25 минут по каждому.

**Comment by ilirhin** [comment]
Пришли мне блокнот, я посмотрю код, может что-то неэффективно реализовано. У меня всё за 20 минут считается, но машинка весьма мощная.

**Comment by ilirhin** [comment]
Я осознал комментарий, в течение часа это суммарное время на подсчет задания. Самая долгая часть считается за 4-5 минут. Представьте, что данных в 50 раз больше, тогда от реализации будет зависеть успеете вы за сутки подсчитать или за 3 суток. Но мы не рискнули давать задание, в котором надо комп на ночь считаться ставить.

**Comment by ilirhin** [comment]
Идейно надо подсчитать за суммарное время, которое примерно в 10 раз больше чем время подсчёта среднего. Этот момент я ещё уточню

**Comment by ilirhin** [comment]
Если измерять время работы функций временем работы функции example, то примерное время работы такое:
Одновременно среднее, среднее - 1.17
Одновременно минимум, максимум и медиана:
easy - 0.87
medium - 2.11
nightmare - 2.85

**Comment by zachanton** [comment]
Спасибо!
