### ISSUE TITLE
theano, логрегрессия

### ISSUE THREAD

**Issue by tveritinova** [vkantor/MIPT_Data_Mining_In_Action_2016#34]
Ошибка в логрегрессии в задании по theano. Не представляю, что с этим делать :(

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-136-81805dde9848> in <module>()
      2 
      3 for i in range(5):
----> 4     loss_i = train_function(X_train,y_train)
      5     print "loss at iter %i:%.4f"%(i,loss_i)
      6     print "train auc:",roc_auc_score(y_train,predict_function(X_train))

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    176         for subtr in tr:
    177             traceback.print_list(subtr, sio)
--> 178         detailed_err_msg += str(sio.getvalue())
    179     else:
    180         hints.append(

UnicodeEncodeError: 'ascii' codec can't encode characters in position 1486-1498: ordinal not in range(128)

**Comment by tveritinova** [comment]
https://github.com/tveritinova/MIPT_Data_Mining_In_Action_2016/blob/master/trends/hw1/theano.ipynb 
в конце

**Comment by senya-ashukha** [comment]
Код что-ли скинь

**Comment by senya-ashukha** [comment]
Привет, да ошибка тупая, на вскидку несколько проблем 
- ты не используешь внутри матричное умножение ни разу -- \* не матричное умножение 
- math.e *\* -> np.exp
- .ravel() --> эт прям очень кривая штука
-  T.sum(input_y_input_X_grad) -- это число а обновлять веса по числу это не хорошо
