### ISSUE TITLE
[industry] hw_0_result

### ISSUE THREAD

**Issue by jeipiem** [vkantor/MIPT_Data_Mining_In_Action_2016#5]
Всем привет!
Получила результаты, проверила вручную на коротких входных данных, тут все ок. Проблема в том, что итоговые ответы по выборкам train и test после запятой имеют 3-4 нуля. То есть м.б. я получила неправильный результат/ не поняла условия или определения/  так и должно быть, хотелось бы получить комментарий.

**Comment by ilirhin** [comment]
Приветствую. Правильные ответы имеют порядок 0.1-0.9. Когда усредняем precision@k или recall@k по сессиям надо усреднять только для тех сессий, в которых были покупки, возможно в этом проблема.

**Comment by jeipiem** [comment]
@vkantor да, в этом проблема, спасибо!

**Comment by jeipiem** [comment]
@ilirhin да, в этом проблема, спасибо!

**Comment by s-stupnikov** [comment]
@ilirhin , спасибо за разъяснение, оно крайне полезно. Мне кажется это не совсем очевидный нюанс, может стоит добавить его в описание задачи?

**Comment by ilirhin** [comment]
Да, всё верно, добавили в условие.

**Comment by dashafok** [comment]
условие не изменено
