### ISSUE TITLE
Скорость обучения

### ISSUE THREAD

**Issue by od2elf** [vkantor/MIPT_Data_Mining_In_Action_2016#6]
Как определить сколько потребуется времени на обучение сети?
Сколько должно занимать в среднем?
Какие есть варианты ускорения обучения, если у меня есть только ноут с виндой? Будет ли принципиально лучше, если поставить юбунту?
Интересует задача для трека "Тренды" - стоит уже более 3х часов, даже 1 эпоха не прошла.

**Comment by senya-ashukha** [comment]
Добрый день, попробуйте сделать не большую, не глубокую сеть input-200-50-200-out, должно сойтись примерно за 10-20 эпох (проходов по данным); думаю что на cpu одна эпоха будет занимать несколько минут, но с этим ничего не сделать, операционка тут не причем; 

Пожалуйста проверьте что у вас загружен хотя-бы 1 процессор, возможно вы что-то не так установили, в этом случаи линукс поможет;

Я надеюсь у Вас не интел атом?=)

**Comment by od2elf** [comment]
И вам доброго вечера =))
Проц - intel CORE i5-4200. Судя по таскменеджеру питон ест 30+% от него.
Сделал сеть Input-196-10-out - по ходу даже еще меньше, чем надо бы...
По ходу пора менять машинку?

**Comment by senya-ashukha** [comment]
пора операционку менять=)) 30 % загрузки это не нормально, у меня это минуты на маке 5 летней давности =)

**Comment by kirillbobyrev** [comment]
@od2elf иногда такое бывает, что IPython Notebook забивает память слишком сильно. Если при перезапуске всё ОК, то проблема в IPython Notebook, а если это систематичное явление, то да, действительно дело скорее всего с операционкой.

**Comment by kirillbobyrev** [comment]
"перезапуск" - это с перезапуском IPython Kernel, разумеется.
