### ISSUE TITLE
AttributeError: module 'xgboost' has no attribute 'DMatrix'

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [vkantor/MIPT_Data_Mining_In_Action_2016#7]
Добрый день! 
Пробовал бенчмар по спортивной секции и скачал xgboost. Почему-то получаю следующую ошибку. Пытался ее гуглить, но ничего особо не понял. 

AttributeError                            Traceback (most recent call last)
<ipython-input-30-27ef42b1358e> in <module>()
----> 1 Xdatatrain = xgboost.DMatrix(data = xtrain, label = ytrain)
      2 Xdatatest = xgboost.DMatrix(data = xval, label = yval)
      3 
      4 plst = list(param.items())
      5 watchlist = [(Xdatatrain, 'train'), (Xdatatest, 'eval')]

AttributeError: module 'xgboost' has no attribute 'DMatrix'

что делать?

**Comment by YaroslavShchekaturov** [comment]
В терминале получел следющее сообщение
Users-MacBook-Air:/ user$ git clone --recursive https://github.com/dmlc/xgboost
fatal: could not create work tree dir 'xgboost': Permission denied

**Comment by YaroslavShchekaturov** [comment]
на сайте http://xgboost.readthedocs.io/en/latest/build.html#building-on-osx сказано 

NOTE: If you use OSX El Capitan, brew installs gcc the latest version gcc-6. So you may need to modify Makefile#L46 and change gcc-5 to gcc-6. After that change gcc-5/g++-5 to gcc-6/g++-6 in make/config.mk then build using the following commands

у меня OSX El Capitan. как мне модифицировать Makefile#L46?

**Comment by aguschin** [comment]
Какая версия хгбуста? 

`xgboost.__version__`

Как он был установлен? Если через git clone из репозитория, попробуй импортировать вот так:

```
import sys
sys.path.append("<PATH TO THE XGBOOST MASTER FOLDER>/xgboost/wrapper/")
import xgboost
```

**Comment by YaroslavShchekaturov** [comment]
устанавливал по алгоритму с сайта http://xgboost.readthedocs.io/en/latest/build.html#building-on-osx

1 brew install gcc --without-multilib
2 git clone --recursive https://github.com/dmlc/xgboost
3 cd xgboost; cp make/minimum.mk ./config.mk; make -j4 (мне кажется эта штука не работает, терминал выдает :
cp: make/config.mk: No such file or directory
make: **\* No targets specified and no makefile found.  Stop.

попытался выполнить :
<img width="1041" alt="2016-10-10 12 10 28" src="https://cloud.githubusercontent.com/assets/22734034/19231422/9549c534-8ee2-11e6-8fd6-d6fc9ad2c0d7.png">

А какие файлы папка содержит? просто у меня их несколько

**Comment by YaroslavShchekaturov** [comment]
в файле VERSION пишет 0.6

**Comment by aguschin** [comment]
`cp make/minimum.mk ./config.mk` должно скопировать файл.
можешь проверить глазами, что существует файл xgboost/make/minimum.mk и скопировать его как xgboost/config.mk ? Потом продолжить с `make -j4`

**Comment by YaroslavShchekaturov** [comment]
прописал вручную cd /Users/user/xgboost/

потом cp make/minimum.mk ./config.mk 

потом make -j4 

после этого началась какая-то движуха в терминале и на выходе 
<img width="565" alt="2016-10-11 0 26 51" src="https://cloud.githubusercontent.com/assets/22734034/19251722/6dd7046e-8f49-11e6-9c12-b80ac9995cfd.png">

попробовал скомпилить опять и опять получил туже ошибку module 'xgboost' has no attribute 'DMatrix'

закрыл терминал и попробовал тоже самое 

прописал вручную cd//Users/user/xgboost/make

потом cp make/minimum.mk ./config.mk 

потом make -j4 
после этого получил 
make: Nothing to be done for `all'.

Может я неправильно делаю? Я 
1) открываю терминал 
2) прописываю все команды 
cd /Users/user/xgboost

cp make/minimum.mk ./config.mk

make -j4

3) открываю jupiter (который отдельно открывает свои терминал)
4) компилю
5) опять получаю ошибку

у меня El Capitan  джаст ин кейс

**Comment by s-stupnikov** [comment]
я тоже ручками собирал, у меня так получилось:
1. git clone --recursive https://github.com/dmlc/xgboost
2. cd xgboost/; sudo ./build.sh
3. cd python-package; sudo python setup.py install

**Comment by kirillbobyrev** [comment]
Если через Anaconda питон стоит, IMHO куда проще установить из user package.

``` bash
anaconda search -t conda xgboost
```

И потом выбрать по версии и платформе.

Из плюсов: не надо самостоятельно обновлять при новых релизах, если user package популярный и его мейнтейнер сам всё обновляет.

**Comment by YaroslavShchekaturov** [comment]
Спасибо огромное ! Вроде заработало!!
