### ISSUE TITLE
Часть "Соберем нейросеть".

### ISSUE THREAD

**Issue by Sergey1983** [vkantor/MIPT_Data_Mining_In_Action_2016#8]
"Мы хотим сделать нейросеть, которая будет принимать картинку (вектор 28 x 28) и сжимать ее в вектор длины 10 (к примеру). Нашим основным инструментом будет lasagne.layers.DenseLayer."
а где можно получить информацию о том, как описывается нейросеть в lasagne? Курс ориентирован на тех, кто уже делал нейросети на Python?
http://joxi.ru/YmEVy5WSZd9PQ2
тут поставил средний слой "тупо по аналогии", взяв его из примеров в http://lasagne.readthedocs.io/en/latest/modules/layers/dense.html

почему у нас в последнем слое как вводный слой берется первый слой (net), а не средний (mid)?

Вообще, хотелось бы понять, на слушателей с какой подготовкой ориентированы эти семинары...
Пока что на первой лекции нам рассказали все в самых общих чертах, а здесь уже требуется разбираться в коде нейросетей, хотя про них ничего не говорилось...

Я один такой "тупой" или все остальные просто молчат?:)

**Comment by senya-ashukha** [comment]
> почему у нас в последнем слое как вводный слой берется первый слой (net), а не средний (mid)?

это исключительно мотивация сделать не один скрытый слой

> Вообще, хотелось бы понять, на слушателей с какой подготовкой ориентированы эти семинары...

очень бы хотелось, чтобы слушатели умели гуглить, и очень хотели научится работать машинным обучением, там-же большими буквами написано, что  **пугаться не нужно**! =)

> а здесь уже требуется разбираться в коде нейросетей, хотя про них ничего не говорилось...

Говорилось. А вот теперь представьте, сколько всего вы будите знать через 3 месяца =)

**Comment by Sergey1983** [comment]
:) Говорилось только то, что "на этом работают гугл мобили, а стандартные классификаторы там не работают". А тут сразу "давайте получим градиенты для обучения"....:)

Окей, попробую доделать эту домашку, может что-то получится. Но пока ощущение как от советских "научно-популярных" книжек, где открываешь и видишь на каждой странице по 30 формул, и думаешь, что имел в виду автор под словом "популярность":)
